"""
Seed: baby_names
Run: python alembic/seeds/baby_names.py
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from app.core.database import AsyncSessionLocal
from app.models.baby_names import BabyName

NAMES = [
    # (name, gender, origin, meaning, popularity_score, trend)
    # ── Femininos ─────────────────────────────────────────────
    ("Sofia", "female", "Grego", "sabedoria", 95, "rising"),
    ("Alice", "female", "Germânico", "nobre e de boa índole", 92, "rising"),
    ("Maria", "female", "Hebraico", "amada por Deus", 90, "stable"),
    ("Valentina", "female", "Latino", "forte e saudável", 89, "rising"),
    ("Isabela", "female", "Hebraico", "consagrada a Deus", 88, "stable"),
    ("Julia", "female", "Latino", "jovial, cheia de vida", 87, "stable"),
    ("Laura", "female", "Latino", "coroa de louros", 85, "stable"),
    ("Ana", "female", "Hebraico", "cheia de graça", 84, "stable"),
    ("Beatriz", "female", "Latino", "ela que traz alegria", 84, "stable"),
    ("Olivia", "female", "Latino", "símbolo de paz, oliveira", 83, "rising"),
    ("Luna", "female", "Latino", "lua", 83, "rising"),
    ("Mariana", "female", "Latino", "cheia de graça e mar", 82, "stable"),
    ("Cecilia", "female", "Latino", "músico cego", 81, "rising"),
    ("Clara", "female", "Latino", "clara e brilhante", 80, "rising"),
    ("Leticia", "female", "Latino", "alegria e felicidade", 80, "stable"),
    ("Mia", "female", "Escandinavo", "minha amada", 79, "rising"),
    ("Maya", "female", "Sânscrito", "ilusão, mãe", 79, "rising"),
    ("Emma", "female", "Germânico", "inteira e universal", 78, "rising"),
    ("Luisa", "female", "Germânico", "guerreira famosa", 78, "rising"),
    ("Helena", "female", "Grego", "brilhante como o sol", 77, "stable"),
    ("Camila", "female", "Latino", "serva do templo", 77, "stable"),
    ("Giovanna", "female", "Hebraico", "Deus é gracioso", 76, "rising"),
    ("Amelia", "female", "Germânico", "trabalho e esforço", 76, "rising"),
    ("Natalia", "female", "Latino", "nascida no Natal", 75, "stable"),
    ("Lara", "female", "Grego", "famosa, protetora", 75, "rising"),
    ("Aurora", "female", "Latino", "aurora, amanhecer", 75, "rising"),
    ("Nina", "female", "Eslavo", "graça de Deus", 74, "rising"),
    ("Stella", "female", "Latino", "estrela", 74, "rising"),
    ("Catarina", "female", "Grego", "pura e casta", 74, "rising"),
    ("Pietra", "female", "Grego/Italiano", "pedra firme", 73, "rising"),
    ("Rafaela", "female", "Hebraico", "Deus cura", 73, "stable"),
    ("Gabriela", "female", "Hebraico", "força de Deus", 72, "declining"),
    ("Elisa", "female", "Hebraico", "prometida a Deus", 72, "rising"),
    ("Bianca", "female", "Italiano", "branca e pura", 72, "declining"),
    ("Isadora", "female", "Grego", "presente de Ísis", 72, "rising"),
    ("Theodora", "female", "Grego", "presente de Deus", 71, "rising"),
    ("Carolina", "female", "Germânico", "mulher forte e livre", 71, "declining"),
    ("Vitoria", "female", "Latino", "vitória", 71, "stable"),
    ("Penelope", "female", "Grego", "tecelã fiel", 70, "rising"),
    ("Manuela", "female", "Hebraico", "Deus está conosco", 70, "stable"),
    ("Livia", "female", "Latino", "pálida, oliváceo", 70, "stable"),
    ("Yasmin", "female", "Árabe", "flor de jasmim", 69, "rising"),
    ("Chloe", "female", "Grego", "jovem rebento verde", 69, "rising"),
    ("Iris", "female", "Grego", "arco-íris", 69, "rising"),
    ("Elora", "female", "Hebraico", "Deus é luz", 68, "rising"),
    ("Eva", "female", "Hebraico", "vida", 68, "stable"),
    ("Lily", "female", "Inglês", "lírio, pureza", 68, "rising"),
    ("Nora", "female", "Irlandês", "honra e luz", 67, "rising"),
    ("Antonia", "female", "Latino", "inestimável", 67, "rising"),
    ("Lorena", "female", "Latino", "glória", 66, "stable"),
    ("Rebeca", "female", "Hebraico", "laço que une", 66, "stable"),
    ("Laila", "female", "Árabe", "nascida à noite", 65, "rising"),
    ("Larissa", "female", "Grego", "alegre e despreocupada", 65, "stable"),
    ("Paloma", "female", "Espanhol", "pomba da paz", 64, "stable"),
    ("Melissa", "female", "Grego", "abelha, doce como mel", 63, "declining"),
    ("Fernanda", "female", "Germânico", "viajante corajosa", 62, "declining"),
    ("Amanda", "female", "Latino", "digna de amor", 61, "declining"),
    ("Juliana", "female", "Latino", "jovial e alegre", 60, "declining"),
    ("Miriam", "female", "Hebraico", "amada, exaltada", 60, "stable"),
    ("Vanessa", "female", "Grego", "borboleta", 59, "declining"),
    ("Simone", "female", "Hebraico", "que escuta", 58, "declining"),
    ("Viviane", "female", "Latino", "viva e cheia de vida", 57, "stable"),
    ("Patricia", "female", "Latino", "nobre, de origem nobre", 56, "declining"),
    ("Monica", "female", "Grego", "solitária, única", 55, "declining"),
    ("Daniela", "female", "Hebraico", "Deus é meu juiz", 55, "declining"),
    ("Renata", "female", "Latino", "renascida", 54, "declining"),
    ("Veronica", "female", "Grego/Latino", "imagem verdadeira", 54, "declining"),
    ("Claudia", "female", "Latino", "de família Cláudia", 53, "declining"),
    ("Priscila", "female", "Latino", "antiga e venerável", 52, "declining"),
    ("Bruna", "female", "Germânico", "morena, pele escura", 52, "declining"),
    ("Thais", "female", "Grego", "querida e amada", 51, "declining"),
    ("Ingrid", "female", "Escandinavo", "beleza de Ing", 50, "stable"),
    ("Raquel", "female", "Hebraico", "ovelha inocente", 50, "stable"),
    ("Alessandra", "female", "Grego", "defensora dos homens", 49, "declining"),
    ("Andrea", "female", "Grego", "corajosa e valente", 48, "declining"),
    ("Flavia", "female", "Latino", "loira, de cabelos dourados", 47, "declining"),
    ("Carla", "female", "Germânico", "mulher livre", 47, "declining"),
    ("Sandra", "female", "Grego", "defensora dos homens", 46, "declining"),
    ("Tatiana", "female", "Eslavo", "fada rainha", 45, "declining"),
    ("Luciana", "female", "Latino", "que traz luz", 44, "declining"),
    ("Denise", "female", "Grego", "devota de Dionísio", 43, "declining"),
    ("Michelle", "female", "Hebraico", "quem é como Deus", 43, "declining"),
    ("Andressa", "female", "Grego", "feminina e corajosa", 42, "declining"),
    ("Nathalia", "female", "Latino", "nascida no dia do Natal", 41, "declining"),
    ("Fabiola", "female", "Latino", "feijão, cultivo", 40, "declining"),
    ("Eliane", "female", "Hebraico", "meu Deus é o Senhor", 39, "declining"),
    ("Soraya", "female", "Persa", "princesa das estrelas", 38, "declining"),
    ("Glaucia", "female", "Grego", "cinza-esverdeado", 35, "declining"),
    ("Celia", "female", "Latino", "do céu, celestial", 34, "declining"),
    ("Magali", "female", "Grego", "pérola preciosa", 33, "declining"),
    ("Roberta", "female", "Germânico", "fama brilhante", 32, "declining"),
    ("Lia", "female", "Hebraico", "cansada, fiel", 73, "rising"),
    ("Jade", "female", "Espanhol", "pedra preciosa verde", 72, "rising"),
    ("Kiara", "female", "Grego/Latino", "clara e brilhante", 70, "rising"),
    ("Gaia", "female", "Grego", "mãe terra, terra", 69, "rising"),
    ("Serena", "female", "Latino", "serena e tranquila", 69, "rising"),
    ("Hannah", "female", "Hebraico", "cheia de graça", 67, "stable"),
    ("Naomi", "female", "Hebraico", "minha delícia", 66, "rising"),
    ("Freya", "female", "Escandinavo", "nobre senhora", 66, "rising"),
    ("Talia", "female", "Hebraico", "orvalho de Deus", 65, "rising"),
    ("Lena", "female", "Grego", "luz do sol", 65, "rising"),
    ("Esther", "female", "Hebraico/Persa", "estrela, escondida", 64, "rising"),
    ("Daphne", "female", "Grego", "loureiro, triunfo", 63, "rising"),
    ("Vera", "female", "Latino/Russo", "verdade, fé", 62, "rising"),
    ("Anya", "female", "Russo", "graça de Deus", 61, "rising"),
    ("Uma", "female", "Sânscrito", "esplendor, tranquilidade", 60, "rising"),
    # ── Masculinos ────────────────────────────────────────────
    ("Miguel", "male", "Hebraico", "quem é como Deus", 96, "rising"),
    ("Arthur", "male", "Celta", "urso, nobre", 94, "rising"),
    ("Bernardo", "male", "Germânico", "urso corajoso", 90, "rising"),
    ("Heitor", "male", "Grego", "o que segura firme", 88, "rising"),
    ("Samuel", "male", "Hebraico", "ouvido por Deus", 87, "stable"),
    ("Pedro", "male", "Grego", "pedra, rocha", 86, "stable"),
    ("Gabriel", "male", "Hebraico", "força de Deus", 86, "stable"),
    ("Davi", "male", "Hebraico", "amado de Deus", 85, "rising"),
    ("Lucas", "male", "Grego/Latino", "luz, brilhante", 85, "stable"),
    ("Matheus", "male", "Hebraico", "presente de Deus", 84, "stable"),
    ("Theo", "male", "Grego", "presente de Deus", 84, "rising"),
    ("Enzo", "male", "Germânico/Italiano", "senhor da casa", 83, "rising"),
    ("Rafael", "male", "Hebraico", "Deus cura", 83, "stable"),
    ("Lorenzo", "male", "Latino", "natural de Laurento", 82, "rising"),
    ("Gustavo", "male", "Escandinavo", "bastão dos godos", 80, "stable"),
    ("Felipe", "male", "Grego", "amigo dos cavalos", 80, "stable"),
    ("João", "male", "Hebraico", "Deus é gracioso", 80, "stable"),
    ("Nicolas", "male", "Grego", "vitória do povo", 79, "rising"),
    ("Eduardo", "male", "Inglês Antigo", "guardião da prosperidade", 78, "stable"),
    ("Leonardo", "male", "Germânico", "leão corajoso", 78, "stable"),
    ("Rodrigo", "male", "Germânico", "glória famosa", 76, "declining"),
    ("Bruno", "male", "Germânico", "moreno, pele escura", 75, "declining"),
    ("Diego", "male", "Espanhol", "que substitui", 75, "stable"),
    ("Thiago", "male", "Hebraico", "que substitui", 75, "stable"),
    ("Vitor", "male", "Latino", "vitorioso", 74, "stable"),
    ("Caio", "male", "Latino", "alegre, que se regozija", 74, "rising"),
    ("Iago", "male", "Hebraico", "que substitui", 73, "rising"),
    ("Henrique", "male", "Germânico", "governante do lar", 73, "stable"),
    ("Otavio", "male", "Latino", "oitavo filho", 72, "rising"),
    ("Vicente", "male", "Latino", "que vence", 72, "rising"),
    ("Benjamin", "male", "Hebraico", "filho da mão direita", 71, "rising"),
    ("Luca", "male", "Grego/Latino", "luz, luminoso", 71, "rising"),
    ("Augusto", "male", "Latino", "augusto e majestoso", 70, "rising"),
    ("Marcelo", "male", "Latino", "pequeno guerreiro de Marte", 70, "declining"),
    ("Daniel", "male", "Hebraico", "Deus é meu juiz", 69, "stable"),
    ("Andre", "male", "Grego", "corajoso e valente", 68, "declining"),
    ("Carlos", "male", "Germânico", "homem livre e forte", 67, "declining"),
    ("Marcos", "male", "Latino", "dedicado a Marte", 66, "declining"),
    ("Paulo", "male", "Latino", "pequeno, humilde", 65, "declining"),
    ("Fernando", "male", "Germânico", "viajante corajoso", 64, "declining"),
    ("Ricardo", "male", "Germânico", "rei poderoso", 63, "declining"),
    ("Roberto", "male", "Germânico", "fama brilhante", 62, "declining"),
    ("Alexandre", "male", "Grego", "defensor dos homens", 62, "declining"),
    ("Luciano", "male", "Latino", "que traz luz", 60, "declining"),
    ("Renato", "male", "Latino", "renascido", 58, "declining"),
    ("Fabio", "male", "Latino", "feijão, cultivo", 56, "declining"),
    ("Sergio", "male", "Latino", "guardião", 55, "declining"),
    ("Claudinho", "male", "Latino", "de família Cláudia", 50, "declining"),
    ("Vagner", "male", "Germânico", "condutor de carroças", 45, "declining"),
    ("Edson", "male", "Inglês Antigo", "filho de Ed", 43, "declining"),
    ("Gilberto", "male", "Germânico", "refém brilhante", 40, "declining"),
    ("Waldir", "male", "Germânico", "governante da floresta", 38, "declining"),
    ("Laercio", "male", "Grego", "chefe do exército", 35, "declining"),
    ("Mateo", "male", "Hebraico", "presente de Deus", 72, "rising"),
    ("Oliver", "male", "Latino", "oliveira, símbolo de paz", 71, "rising"),
    ("Sebastian", "male", "Grego", "venerável, respeitável", 70, "rising"),
    ("Leon", "male", "Grego", "leão, corajoso", 69, "rising"),
    ("Felix", "male", "Latino", "feliz e afortunado", 69, "rising"),
    ("Ethan", "male", "Hebraico", "forte e firme", 68, "rising"),
    ("Julian", "male", "Latino", "jovial, de família Júlia", 67, "rising"),
    ("Nathan", "male", "Hebraico", "Deus deu, presente", 66, "rising"),
    ("Dylan", "male", "Galês", "filho do mar", 65, "rising"),
    ("Aaron", "male", "Hebraico", "montanha de força", 65, "rising"),
    ("Ryan", "male", "Irlandês", "rei pequeno", 63, "rising"),
    ("Ivan", "male", "Eslavo", "Deus é gracioso", 60, "stable"),
    ("Kaio", "male", "Grego", "alegre, que se regozija", 62, "rising"),
    ("Tomas", "male", "Hebraico", "gêmeo", 64, "stable"),
    ("Calvin", "male", "Latino", "de família Calvino", 55, "rising"),
    # ── Neutros / Unissex ─────────────────────────────────────
    ("Ari", "neutral", "Hebraico", "leão de Deus", 72, "rising"),
    ("Alex", "neutral", "Grego", "defensor do povo", 70, "stable"),
    ("Bento", "neutral", "Latino", "abençoado", 68, "rising"),
    ("Cris", "neutral", "Grego", "portador de Cristo", 60, "stable"),
    ("Dani", "neutral", "Hebraico", "Deus é meu juiz", 62, "stable"),
    ("Eden", "neutral", "Hebraico", "paraíso, delícia", 65, "rising"),
    ("Eli", "neutral", "Hebraico", "elevado, sublime", 66, "rising"),
    ("Gio", "neutral", "Hebraico", "Deus é gracioso", 60, "rising"),
    ("Jordan", "neutral", "Hebraico", "que desce, rio", 63, "rising"),
    ("Kim", "neutral", "Coreano", "ouro, valioso", 55, "stable"),
    ("Lane", "neutral", "Inglês", "caminho estreito", 52, "rising"),
    ("Morgan", "neutral", "Galês", "brilhante do mar", 58, "rising"),
    ("Nael", "neutral", "Árabe", "bem-sucedido", 64, "rising"),
    ("Noah", "neutral", "Hebraico", "repouso, consolo", 75, "rising"),
    ("Rio", "neutral", "Espanhol/Japonês", "rio, aldeia", 68, "rising"),
    ("Robin", "neutral", "Germânico", "fama brilhante", 60, "stable"),
    ("Ryo", "neutral", "Japonês", "excluente, refrescante", 55, "rising"),
    ("Sam", "neutral", "Hebraico", "ouvido por Deus", 62, "stable"),
    ("Sky", "neutral", "Inglês", "céu, firmamento", 58, "rising"),
    ("Sol", "neutral", "Latino", "sol, luz", 65, "rising"),
    ("Tay", "neutral", "Inglês", "alfaiate", 50, "rising"),
    ("Uri", "neutral", "Hebraico", "minha chama, luz", 57, "rising"),
    ("Vale", "neutral", "Latino", "vale, saudável", 52, "rising"),
    ("Zion", "neutral", "Hebraico", "monumento, sinal", 60, "rising"),
    ("Ash", "neutral", "Inglês", "freixo, árvore forte", 63, "rising"),
    ("Ren", "neutral", "Japonês", "lótus, amor puro", 61, "rising"),
    ("Indigo", "neutral", "Grego", "azul profundo, intuição", 57, "rising"),
    ("Demi", "neutral", "Grego", "metade, do povo", 58, "rising"),
    ("Blue", "neutral", "Inglês", "azul, calmo como o céu", 55, "rising"),
]


async def run():
    async with AsyncSessionLocal() as db:
        existing = (
            await db.execute(__import__("sqlalchemy").select(__import__("sqlalchemy").func.count()).select_from(BabyName))
        ).scalar_one()
        if existing > 0:
            print(f"Skipping: {existing} baby names already seeded.")
            return

        records = [
            BabyName(
                name=name,
                gender=gender,
                origin=origin,
                meaning=meaning,
                popularity_score=popularity_score,
                trend=trend,
            )
            for name, gender, origin, meaning, popularity_score, trend in NAMES
        ]
        db.add_all(records)
        await db.commit()
        print(f"Seeded {len(records)} baby names.")


if __name__ == "__main__":
    asyncio.run(run())
