version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: lunna_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: lunna_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

volumes:
  postgres_data:
  redis_data:
